### ISSUE TITLE
Plugin?

### ISSUE THREAD

**Issue by Chefkeks** [zerodha/osticket-archive#1]
Hi there,

stumbled across this repo here and thought it would be great to have this archive functionality as a plugin available.

We have written a standalone script to sync info from ldap to osTicket (takes look at my repos), but having it working as a plugin is our goal. Unfortunately we miss time and knowledge, but that's our business ;)

So since you seem to have knowledge and hopefully also time, you shall consider creating a plugin for osTicket. 

Unfortunately there is no official plugin development guide for osTicket since the plugin system is not yet finished / fully integrated, but you can take a look at the following unofficial guide:
http://osticket.com/forum/discussion/77864/unofficial-plugin-development-guide#latest

That's all. Keep up the good work :)

Cheers,
Michael

**Comment by knadh** [comment]
@Chefkeks, thanks! Unfortunately, time's still the bottleneck. I'll still see if I can look into turning this into a plugin sometime.

That said, depending on the size of the database, the script could take hours to finish the archival, so it's best run from the terminal. I don't know how practical that would be for a plugin.

**Comment by Chefkeks** [comment]
That's true - it could take really long depending on the size of the database :(

So when you ever make this as osTicket plugin, in my eyes I would make it run in the background (if possible?!) and show then a message bar on top of the agent/admin panel (like the "delete setup directory for security reasons" message bar) in case of success and in case of error email the osTicket admin that the export failed.

Anyway, keep up the good work :+1:  and now closing this "issue" since it's more a comment as an real issue :)

Cheers,
Michael
